apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80         # Cluster port
      targetPort: 3000 # Container port
      nodePort: 30080  # Node port (accessible outside the cluster)
